In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [10]:
a[2]

np.int64(3)

In [11]:
a[2]=10
a

array([ 1,  2, 10,  5,  7, 12])

In [13]:
np.arange(3, 10)


array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [16]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
n  = np.array([
         [1,2,3],
         [4,5,6],
         [7,8,9]
])

In [24]:
n[0,1] = 20

In [25]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [26]:
n[2] = [1,1,1]

In [27]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [29]:
n[:,2] = [1,2,3]

In [30]:
n[:,2]

array([1, 2, 3])

In [31]:
n

array([[ 1, 20,  1],
       [ 4,  5,  2],
       [ 1,  1,  3]])

In [36]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [37]:
np.random.randn(5,2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [38]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [39]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [40]:
b = (10 * a)


In [41]:
b


array([ 0, 10, 20, 30, 40])

In [42]:
a+b

array([ 0, 11, 22, 33, 44])

In [43]:
b >= 2


array([False,  True,  True,  True,  True])

In [44]:
a > b

array([False, False, False, False, False])

In [45]:
b > a

array([False,  True,  True,  True,  True])

In [46]:
a.min()

np.int64(0)

In [47]:
b

array([ 0, 10, 20, 30, 40])

In [48]:
b.min()

np.int64(0)

In [49]:
b.max()

np.int64(40)

In [50]:
a.mean()

np.float64(2.0)