In [1]:
import pandas as pd
import numpy as np

In [2]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv'
!wget $data

--2025-10-13 20:39:48--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/course_lead_scoring.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 80876 (79K) [text/plain]
Saving to: ‘course_lead_scoring.csv’

course_lead_scoring 100%[===================>]  78.98K  --.-KB/s    in 0.002s  

2025-10-13 20:39:48 (40.8 MB/s) - ‘course_lead_scoring.csv’ saved [80876/80876]



In [147]:
df = pd.read_csv('course_lead_scoring.csv')

# Getting Size
df.shape

(1462, 9)

In [148]:
# Looking at the head
df.head()

lead_source    industry  number_of_courses_viewed  annual_income  \
0      paid_ads         NaN                         1        79450.0   
1  social_media      retail                         1        46992.0   
2        events  healthcare                         5        78796.0   
3      paid_ads      retail                         2        83843.0   
4      referral   education                         3        85012.0   

  employment_status       location  interaction_count  lead_score  converted  
0        unemployed  south_america                  4        0.94          1  
1          employed  south_america                  1        0.80          0  
2        unemployed      australia                  3        0.69          1  
3               NaN      australia                  1        0.87          0  
4     self_employed         europe                  3        0.62          1

In [149]:
# Transpose of Head
df.head().T

0              1           2          3  \
lead_source                    paid_ads   social_media      events   paid_ads   
industry                            NaN         retail  healthcare     retail   
number_of_courses_viewed              1              1           5          2   
annual_income                   79450.0        46992.0     78796.0    83843.0   
employment_status            unemployed       employed  unemployed        NaN   
location                  south_america  south_america   australia  australia   
interaction_count                     4              1           3          1   
lead_score                         0.94            0.8        0.69       0.87   
converted                             1              0           1          0   

                                      4  
lead_source                    referral  
industry                      education  
number_of_courses_viewed              3  
annual_income                   85012.0  
employment_status         self_employed  
location                         europe  
interaction_count                     3  
lead_score                         0.62  
converted                             1

In [150]:
# Types inspection
df.dtypes

lead_source                  object
industry                     object
number_of_courses_viewed      int64
annual_income               float64
employment_status            object
location                     object
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [151]:
# getting categorical columns
categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)
categorical_columns

['lead_source', 'industry', 'employment_status', 'location']

In [152]:
# prepare uniform values in column names (not needed but done for practice)
df.columns = df.columns.str.lower().str.replace(' ', '_')

# preparing uniform values in column values
for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')
 
df.head().T

0              1           2          3  \
lead_source                    paid_ads   social_media      events   paid_ads   
industry                            NaN         retail  healthcare     retail   
number_of_courses_viewed              1              1           5          2   
annual_income                   79450.0        46992.0     78796.0    83843.0   
employment_status            unemployed       employed  unemployed        NaN   
location                  south_america  south_america   australia  australia   
interaction_count                     4              1           3          1   
lead_score                         0.94            0.8        0.69       0.87   
converted                             1              0           1          0   

                                      4  
lead_source                    referral  
industry                      education  
number_of_courses_viewed              3  
annual_income                   85012.0  
employment_status         self_employed  
location                         europe  
interaction_count                     3  
lead_score                         0.62  
converted                             1

In [153]:
# filling NAs of categorical_columns
df[categorical_columns] = df[categorical_columns].fillna('NA')
df.head().T

0              1           2          3  \
lead_source                    paid_ads   social_media      events   paid_ads   
industry                             NA         retail  healthcare     retail   
number_of_courses_viewed              1              1           5          2   
annual_income                   79450.0        46992.0     78796.0    83843.0   
employment_status            unemployed       employed  unemployed         NA   
location                  south_america  south_america   australia  australia   
interaction_count                     4              1           3          1   
lead_score                         0.94            0.8        0.69       0.87   
converted                             1              0           1          0   

                                      4  
lead_source                    referral  
industry                      education  
number_of_courses_viewed              3  
annual_income                   85012.0  
employment_status         self_employed  
location                         europe  
interaction_count                     3  
lead_score                         0.62  
converted                             1

In [154]:
# getting numerical columns
numerical_columns = ['number_of_courses_viewed','annual_income','interaction_count','lead_score']
numerical_columns

['number_of_courses_viewed',
 'annual_income',
 'interaction_count',
 'lead_score']

In [155]:
# filling NAs of numerical columns
df[numerical_columns] = df[numerical_columns].fillna(0.0)
df[numerical_columns]

number_of_courses_viewed  annual_income  interaction_count  lead_score
0                            1        79450.0                  4        0.94
1                            1        46992.0                  1        0.80
2                            5        78796.0                  3        0.69
3                            2        83843.0                  1        0.87
4                            3        85012.0                  3        0.62
...                        ...            ...                ...         ...
1457                         1            0.0                  4        0.53
1458                         3        65259.0                  2        0.24
1459                         1        45688.0                  3        0.02
1460                         5        71016.0                  0        0.25
1461                         3        92855.0                  3        0.41

[1462 rows x 4 columns]

In [156]:
# Question 1
df['industry'].mode()

0    retail
Name: industry, dtype: object

In [157]:
# Question 2

#interaction_count and lead_score
df['interaction_count'].corr(df.lead_score)

np.float64(0.009888182496913084)

In [158]:
#number_of_courses_viewed and lead_score
df['number_of_courses_viewed'].corr(df['lead_score'])

np.float64(-0.004878998354681257)

In [159]:
#number_of_courses_viewed and interaction_count
df['number_of_courses_viewed'].corr(df['interaction_count'])

np.float64(-0.023565222882888117)

In [160]:
#annual_income and interaction_count
df['annual_income'].corr(df['interaction_count'])

np.float64(0.02703647240481436)

In [161]:
# Question 3
from sklearn.model_selection import train_test_split

In [162]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
len(df_full_train), len(df_test)

(1169, 293)

In [163]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)
len(df_train), len(df_val)

(876, 293)

In [164]:
# Reset Index
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [165]:
# Prepare y
y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

In [166]:
df_full_train

lead_source       industry  number_of_courses_viewed  annual_income  \
1066  social_media  manufacturing                         2        44403.0   
638         events         retail                         3        38048.0   
799   social_media      education                         2        71399.0   
380       referral      education                         2        47912.0   
303       paid_ads     healthcare                         1        34806.0   
...            ...            ...                       ...            ...   
1130        events  manufacturing                         1        57039.0   
1294        events     healthcare                         2        56185.0   
860       paid_ads  manufacturing                         1        56402.0   
1459      paid_ads     technology                         1        45688.0   
1126        events  manufacturing                         0        43862.0   

     employment_status       location  interaction_count  lead_score  \
1066     self_employed      australia                  1        0.71   
638            student  north_america                  6        0.97   
799                 NA         europe                  1        0.51   
380           employed      australia                  1        0.04   
303           employed         europe                  4        0.32   
...                ...            ...                ...         ...   
1130          employed  south_america                  2        0.30   
1294           student  south_america                  2        0.44   
860            student  north_america                  1        0.02   
1459           student  north_america                  3        0.02   
1126     self_employed           asia                  4        0.21   

      converted  
1066          0  
638           1  
799           1  
380           0  
303           1  
...         ...  
1130          0  
1294          0  
860           0  
1459          1  
1126          0  

[1169 rows x 9 columns]

In [167]:
# Calculate mutual info
from sklearn.metrics import mutual_info_score

def mutual_info_converted_score(series):
    return mutual_info_score(series, df_train.converted)

In [168]:
mi = df_train[categorical_columns].apply(mutual_info_converted_score)
mi.sort_values(ascending=False).round(2)

lead_source          0.04
employment_status    0.01
industry             0.01
location             0.00
dtype: float64

In [169]:
# Question 4 - Train Model

In [170]:
# Delete column converted
del df_train['converted']
del df_val['converted']
del df_test['converted'] 

In [171]:
# One-hot Encoding
from sklearn.feature_extraction import DictVectorizer

In [172]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical_columns + numerical_columns].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical_columns + numerical_columns].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [173]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def logistic_regression(xi):
    score = w0
     
    for j in range(len(w)):
        score = score + xi[j] * w[j]
     
    result = sigmoid(score)
    return result

In [174]:
from sklearn.linear_model import LogisticRegression
 
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [175]:
model.coef_[0].round(3)

array([-0.   , -0.015,  0.034,  0.003,  0.012, -0.103, -0.025,  0.049,
       -0.02 , -0.013, -0.003, -0.009, -0.032, -0.016,  0.311,  0.051,
        0.02 , -0.012, -0.012, -0.115,  0.08 , -0.03 ,  0.004, -0.011,
       -0.011, -0.006,  0.008,  0.006, -0.033, -0.025,  0.454])

In [177]:
# bias
model.intercept_[0]

np.float64(-0.0691472802783609)

In [178]:
model.predict(X_train)

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,

In [179]:
y_pred = model.predict_proba(X_val)[:,1]
y_pred

array([0.61192163, 0.79982617, 0.53021344, 0.47131479, 0.57066132,
       0.44227169, 0.87127669, 0.84883115, 0.83290037, 0.61497801,
       0.54968027, 0.78153088, 0.69039786, 0.77017122, 0.5265944 ,
       0.91706425, 0.53170635, 0.42123049, 0.30146455, 0.84881583,
       0.79488653, 0.73670375, 0.44527211, 0.64838383, 0.4176882 ,
       0.75393418, 0.90166116, 0.33903049, 0.43181431, 0.9680681 ,
       0.92018714, 0.37487988, 0.652301  , 0.90650057, 0.75164117,
       0.64202121, 0.82250075, 0.83375553, 0.659116  , 0.30978853,
       0.78942264, 0.35546366, 0.96517758, 0.63389304, 0.51274195,
       0.53230533, 0.82287785, 0.744074  , 0.73452313, 0.68955217,
       0.46964443, 0.84539252, 0.55635243, 0.92637871, 0.65258021,
       0.61526273, 0.63816995, 0.28304018, 0.48049824, 0.57890618,
       0.35497342, 0.62175051, 0.38960778, 0.61156056, 0.85304278,
       0.75430136, 0.89185954, 0.71946459, 0.95387623, 0.89209517,
       0.75277088, 0.33850139, 0.61376593, 0.51622275, 0.64088

In [180]:
converted_decision = y_pred >0.5
converted_decision

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True, False,  True, False,  True,  True,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False,  True,  True, False,  True,  True, False,  True,  True,
       False,  True,

In [181]:
df_val[converted_decision]

lead_source       industry  number_of_courses_viewed  annual_income  \
0          paid_ads     healthcare                         3        52220.0   
1    organic_search     technology                         3        59656.0   
2            events  manufacturing                         0        57134.0   
4          referral         retail                         1        54103.0   
6    organic_search             NA                         1            0.0   
..              ...            ...                       ...            ...   
285        referral      education                         3            0.0   
286          events     technology                         1            0.0   
287          events         retail                         5        69305.0   
289        paid_ads             NA                         1        20326.0   
291  organic_search     technology                         2        39103.0   

    employment_status       location  interaction_count  lead_score  
0          unemployed         europe                  1        0.07  
1          unemployed    middle_east                  4        0.65  
2       self_employed  north_america                  4        0.13  
4          unemployed  south_america                  3        0.16  
6             student           asia                  5        0.14  
..                ...            ...                ...         ...  
285        unemployed           asia                  0        0.16  
286          employed           asia                  2        0.18  
287        unemployed      australia                  3        0.32  
289          employed    middle_east                  3        0.81  
291     self_employed         africa                  3        0.60  

[235 rows x 8 columns]

In [184]:
# Accuracy
(y_val == converted_decision).mean().round(2)

np.float64(0.7)